/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  howto: [
    'how-to-intro',
    {
      type: 'category',
      label: 'How to',
      collapsed: false,
      collapsible: false,
      items: [
        {
          type: 'autogenerated',
          dirName: 'how-to',
        },
      ],
    },
  ],
  ref: [
    'ref-intro',
    {
      type: 'category',
      label: 'Reference',
      collapsed: false,
      collapsible: false,
      items: [
        {
          type: 'autogenerated',
          dirName: 'ref',
        },
      ],
    },
  ],
  exp: [
    'exp-intro',
    {
      type: 'category',
      label: 'Explanation',
      collapsed: false,
      collapsible: false,
      items: [
        {
          type: 'autogenerated',
          dirName: 'exp',
        },
      ],
    },
  ],
};

module.exports = sidebars;
